[features]
seeds = false
[programs.mainnet]
coin_flip = "EZgGhv1i3LSEA2sVkWr5HHWuS4cwYo6XHqdPopjjNVV5"
[programs.devnet]
coin_flip = "EZgGhv1i3LSEA2sVkWr5HHWuS4cwYo6XHqdPopjjNVV5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/mertozgun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
